### ISSUE TITLE
Bug on adding series of existing study

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO_Uploader#37]
Possibilité d'uploader une nouvelle série sans devoir supprimer toutes celles déjà chargées (notamment pour les actions correctives)

**Comment by salimkanoun** [comment]
En fait ce n'est pas possible, tout les dicom sont identifié par des clé
uniques sur le studyInstanceUID, SeriesInstanceUID et SopInstanceUID
Lors de l anonymisation on doit régénérer ces uid car sinon tu garde une
clé identifiant et c'est en plus une règle du dicom, quand tu change un
dicom tu dois changer ces uid qui doivent être unique dans le monde entier.

Il faudrait pour ajouter une série forcer côté serveur a utiliser le même
studyUID mais dans les dicom y a d'autre référence de certaines instance
UID pour définir une coupe de référence dans la study

Bref c'est quasiment impossible.

Je leur ai expliqué mais ils sont frustrés car d'autre CRO permettent ça,
en fait ils ne changent pas les studyInstanceUID et ils font une
anonymisation defaillante.

Pour l instant faut pas aller vers ça, c'est une terrain très casse gueule.

Le ven. 7 août 2020 à 12:38, EmilieOLIVIE <notifications@github.com> a
écrit :
