### ISSUE TITLE
Hide field feature

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO_Uploader#38]
Possibilité de réduire le tableau des séries (ne pas afficher tous les champs)

**Comment by salimkanoun** [comment]
@EmilieOLIVIE je suis pas très convaincu par l'utilité, ca surchage l'interface, vaut mieux qu'elle reste la plus simple possible.
C'est quelque chose que t'a demandé Clara ?

**Comment by EmilieOLIVIE** [comment]
Oui, c’était un des points d’amélioration qu’ils proposaient. Je suis d’accord pour l’utilité; je ne savais même pas trop quels champs rendre hideable...

**Comment by salimkanoun** [comment]
ce que tu peux faire c'est de mettre une icon "options" (https://icons.getbootstrap.com/icons/gear/) a coté des badges (filed loaded, ignored ...)
au click sur l'icon option tu met un overlay avec les settings, donc tu peux mettre ici les colonnes à afficher ou pas et tu peux faire en sorte que ca persiste pour l'utilisateur en utilisant le localstorage du navigateur (https://www.robinwieruch.de/local-storage-react#local-storage-in-react)

Comme ca ca nous ouvre un panel settings sur lequel on peut mettre des trucs optionels pour ce genre de details (peut etre que ca nous sera utile par la suite, et sinon ca perturbe pas les utilisateurs)

**Comment by salimkanoun** [comment]
Dans ce panneau pourrais tu me faire un slider qui sera le size du batch d'envoie. Il y irait de 50 Mo à 1Go avec un defaut de 100Mo
Y a une balance CPU / RAM /  Reseau qui est pas facile a trouver pour l'upload

**Comment by salimkanoun** [comment]
voila une librairie de slider https://material-ui.com/components/slider/
et si tu peux me faire un select qui va de 1 à 9 pour l'instensité du zipage (9 = plus compréssé, moins de volume a envoyer mais beaucoup plus de CPU a consommer) - defaut a 3 

Tout ces settings faudrait les stocker dans le localstore

**Comment by salimkanoun** [comment]
@EmilieOLIVIE en fait je viens de comprendre sur le document je pense qu'ils parlaient pas de ce tableau la, il parlait du tableau en html dans l'interface visite qui liste tout les détails des dicoms présent dans la plateforme (pas dans l'uploader). 
Je pense que tu peux enlever tes hides columns settings, par contre je veux bien le panneau settings pour permettre à l'user de finetune les parametrage d'upload
