### ISSUE TITLE
Display error message when error import

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO_Uploader#39]
Si error during import,  afficher l'erreur (comme indication du mail) et indiquer un contact pour aide (imagerie@lysarc.org) - A tracer dans le Tracker

**Comment by salimkanoun** [comment]
OK pourquoi pas mais ici c'est que pour une erreur d'upload alors qu'elle parlait d'une erreur lors de la validation de l'upload (quand GaelO dézipe, stocke, anonymise, ecrit en DB).
C'est beaucoup plus compliqué à attraper car c'est une opération longue et asynchrone (on autorise l'utilisateur de se deconnecter pendant ce processus serveur).

On va laisser pour la V2.

D'une part car on devrait arriver à faire a ce que ca ne bug plus, ils ont pas encore confiance car j'ai eu a gérer plein de petite subtilité dans le DICOMs qui fait qu'il y a eu plusieurs bugs de validation, mais y aura un moment ou on aura enfin fait le tour.

D'autre part car ca sera plus facile a gérer quand on aura tout le front en react.

**Comment by salimkanoun** [comment]
Cette issue passera coté frontend gaelo

**Comment by salimkanoun** [comment]
DOne
